image:
  file: Dockerfile
ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
checkoutLocation: "wordpress"
workspaceLocation: "."
tasks:
  - name: MySQL
    command: >
        mysqld --initialize-insecure;
        mysqld &
        sleep 5;
        cd $GITPOD_REPO_ROOT;
  - name: Apache
    command: >
        apachectl start;
  - name: Wordpress
    init: wp core download --path=$GITPOD_REPO_ROOT;
    command: >
        chmod 777 $GITPOD_REPO_ROOT/.htaccess;
        cd $GITPOD_REPO_ROOT;
