image:
  file: Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
checkoutLocation: "wordpress"
workspaceLocation: "."
tasks:
  - name: MySQL
    command: >
      mysqld --initialize-insecure;
      mysqld &
      sleep 5;
      cd $GITPOD_REPO_ROOT;
      gp sync-done db;
  - name: Apache
    command: >
      gp sync-await db && apachectl start;
      gp sync-done server;
  - name: Wordpress
    command: >
      gp sync-await server &&
      chmod 777 $GITPOD_REPO_ROOT/.htaccess;
      cd $GITPOD_REPO_ROOT;
      echo "Now installing Wordpress...";
      bash install.sh;
