image:
  file: Dockerfile
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
checkoutLocation: "wordpress"
workspaceLocation: "."
tasks:
  - command: >
    mysqld --initialize-insecure &&
    mysqld &
    sleep 5 &&
    cd $GITPOD_REPO_ROOT &&
    service mysql status &&
    apachectl start &&
    chmod 777 $GITPOD_REPO_ROOT/.htaccess &&
    cd $GITPOD_REPO_ROOT &&
    echo "Now installing Wordpress..." &&
    bash install.sh
